#!/usr/bin/env zsh
set -eu
setopt pipefail

# -------------------------------------------------
# Create local git repository with standard layout
# J Solon – March 2026
# -------------------------------------------------

# -------- CONSTANTS --------
REPO_DIR="$HOME/github/personal"
WHO_ROOT="$REPO_DIR/whoqa"
TEMPLATES="$WHO_ROOT/docs/templates"
ORIGIN_DIR="$PWD"

usage() {
  echo "Usage: make_repo -n <repo_name> [-h]"
  echo ""
  echo "Options:"
  echo "  -n <repo_name>   Name of the repository to create (required)"
  echo "  -h               Display this help message"
  exit 0
}

# -------- PARSE ARGUMENTS --------
REPO_NAME=""

while getopts ":n:h" opt; do
  case $opt in
    n) REPO_NAME="$OPTARG" ;;
    h) usage ;;
    *) usage ;;
  esac
done

# Ensure name was provided
if [[ -z "$REPO_NAME" ]]; then
  echo "❌ Repository name not provided."
  echo "Use lowercase, numbers, and hyphens only."
  usage
fi

# Catch un-quoted two-word names passed as separate args
if [[ $# -gt $OPTIND-1 ]]; then
  echo "❌ Too many arguments. The repository name cannot contain spaces."
  echo "Use lowercase, numbers, and hyphens only."
  usage
fi

# -------- VALIDATE REPO NAME --------
if [[ ! "$REPO_NAME" =~ ^[a-z0-9-]+$ ]]; then
  echo "❌ Invalid repository name."
  echo "Use lowercase, numbers, and hyphens only."
  exit 1
fi

TARGET_DIR="$REPO_DIR/$REPO_NAME"

# -------- CHECK IF REPO ALREADY EXISTS --------
if [[ -d "$TARGET_DIR" ]]; then
  echo "❌ Repository '$REPO_NAME' already exists in $REPO_DIR"
  exit 1
fi

# -------- PREFLIGHT: VERIFY ALL REQUIRED TEMPLATE FILES EXIST --------
echo "Checking required template files..."
typeset -a REQUIRED_FILES=(
  "$DM_ROOT/.gitignore"
  "$DM_ROOT/pyproject.toml"
  "$TEMPLATES/repo_readme.md"
  "$TEMPLATES/CONTRIBUTING.md"
  "$TEMPLATES/settings.json"
  "$TEMPLATES/.Rprofile.template"
  "$TEMPLATES/.Renviron.template"
  "$TEMPLATES/r-packages.conf"
)

PREFLIGHT_OK=true
for f in "${REQUIRED_FILES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "❌ Missing: $f"
    PREFLIGHT_OK=false
  fi
done

if ! $PREFLIGHT_OK; then
  echo ""
  echo "Aborting — ensure all required template files exist before running make_repo."
  exit 1
fi
echo "✅ All required template files found"

# -------- CREATE REPOSITORY --------
echo "Creating repository: $REPO_NAME"
mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"
git init

# -------- DIRECTORY STRUCTURE --------
echo "Creating directory structure..."
typeset -a DIRS=(
  ".github"
  ".vscode"
  "config"
  "lib/sh"
  "lib/stata"
  "lib/python"
  "lib/r"
  "bin"
  "data/raw"
  "data/cleaned"
  "data/analysis"
  "tables"
  "figures"
  "lists"
  "logs"
  "docs"
  "tests"
  "scripts"
  "report"
  "dictionary"
  "env"
)

for dir in "${DIRS[@]}"; do
  mkdir -p "$dir"
done

# -------- ADD .gitkeep ONLY TO LEAF DIRS --------
echo "Adding .gitkeep files to leaf directories..."
for dir in "${DIRS[@]}"; do
  if [[ -z $(find "$dir" -mindepth 1 -type d) ]]; then
    touch "$dir/.gitkeep"
  fi
done

# -------- COPY TEMPLATE FILES --------
# All files guaranteed to exist — verified in preflight above
echo "Copying template files..."

cp "$TEMPLATES/repo_readme.md" "./README.md"
echo "✅ README.md copied"

cp "$TEMPLATES/CONTRIBUTING.md" "./CONTRIBUTING.md"
echo "✅ CONTRIBUTING.md copied"

cp "$DM_ROOT/.gitignore" "./.gitignore"
echo "✅ .gitignore copied"

cp "$DM_ROOT/pyproject.toml" "./pyproject.toml"
sed -i '' "s/^name = .*/name = \"$REPO_NAME\"/" "./pyproject.toml"
echo "✅ pyproject.toml copied (name set to '$REPO_NAME')"

cp "$TEMPLATES/.Rprofile.template" "./.Rprofile"
echo "✅ .Rprofile copied"

cp "$TEMPLATES/.Renviron.template" "./.Renviron"
echo "✅ .Renviron copied"

cp "$TEMPLATES/r-packages.conf" "./r-packages.conf"
echo "✅ r-packages.conf copied"

# Positron / VS Code settings
cp "$TEMPLATES/settings.json" "./.vscode/settings.json"
echo "✅ .vscode/settings.json copied"

# Shared scripts and libraries
if [[ -d "$DM_ROOT/bin" ]] && [[ -n "$(ls -A $DM_ROOT/bin)" ]]; then
  cp -r "$DM_ROOT/bin/." "./bin/"
  echo "✅ bin/ scripts copied"
else
  echo "⚠️  $DM_ROOT/bin is empty or missing, skipping"
fi

if [[ -d "$DM_ROOT/lib" ]] && [[ -n "$(ls -A $DM_ROOT/lib)" ]]; then
  cp -r "$DM_ROOT/lib/." "./lib/"
  echo "✅ lib/ scripts copied"
else
  echo "⚠️  $DM_ROOT/lib is empty or missing, skipping"
fi

# -------- GENERATE .envrc --------
echo "Generating .envrc..."
cat > "./.envrc" <<EOF
# Auto-generated by make_repo on $(date +%Y-%m-%d)
# Project: ${REPO_NAME}

export REPO_ROOT="\$(git rev-parse --show-toplevel)"

export RAW="\$REPO_ROOT/data/raw"
export CLEANED="\$REPO_ROOT/data/cleaned"
export ANALYSIS="\$REPO_ROOT/data/analysis"

export LOGS="\$REPO_ROOT/logs"
export BIN="\$REPO_ROOT/bin"
export LIB="\$REPO_ROOT/lib"
export SCRIPTS="\$REPO_ROOT/scripts"
export CONFIG="\$REPO_ROOT/config"

# Python venv — activate manually if needed, or let Positron handle it
# source "\$REPO_ROOT/env/.venv/bin/activate"

# Add Path to Launch Stata
export STATA_PATH="\$HOME/bin/launch-stata"
# Add Positron CLI and local project bin to PATH
if [ -d "/Applications/Positron.app" ]; then
    PATH_add "/Applications/Positron.app/Contents/Resources/app/bin"
fi
PATH_add bin

EOF
echo "✅ .envrc generated"

# Auto-install project extensions if Positron is present
if command -v positron > /dev/null; then
    echo "----------------------------------------------------"
    echo "📦 Provisioning Positron Extensions..."

    # Install the extensions
    # --force ensures it updates if an older version exists
    positron --install-extension tmonk.stata-workbench --force
    positron --install-extension hwang1022.code2stata --force

    echo "✅ Stata-workbench and code2stata installed successfully."
    echo ""
    echo "Current Extension List:"
    positron --list-extensions
    echo "----------------------------------------------------"
else
    echo "⚠️  Positron CLI not found. Skipping extension installation."
fi

# -------- INITIAL COMMIT --------
git add .
git commit -m "Initial project structure"

# -------- DIRENV ALLOW --------
direnv allow .
cd "$ORIGIN_DIR"

# -------- REPORT --------
echo ""
echo "✅ Repository '$REPO_NAME' created successfully"
echo "   Location : $TARGET_DIR"
echo ""
echo "Next steps:"
echo "   cd $TARGET_DIR"
echo "   make_venv -p        # create .venv and generate uv.lock (if Python needed)"
echo ""
echo "Add a package  : uv add <package>"
echo "Re-sync later  : uv sync"
echo ""
echo "If prompted    : direnv allow"
